CUISINE_PATTERNS = [
    "afghan",
    "american",
    "arabic",
    "asian",
    "australian",
    "bar",
    "barbecue",
    "beer restaurants",
    "belgian",
    "british",
    "cafe",
    "campania",
    "caribbean",
    "catalan",
    "caucasian",
    "central american",
    "central asian",
    "central-italian",
    "chilean",
    "chinese",
    "contemporary",
    "deli",
    "diner",
    "dining bars",
    "european",
    "fast food",
    "french",
    "fusion",
    "gastropub",
    "grill",
    "hawaiian",
    "healthy",
    "indian",
    "indonesian",
    "international",
    "irish",
    "italian",
    "jamaican",
    "japanese",
    "korean",
    "latin",
    "lazio",
    "malaysian",
    "mediterranean",
    "mexican",
    "middle eastern",
    "neapolitan",
    "pizza",
    "polynesian",
    "pub",
    "romana",
    "seafood",
    "soups",
    "southern-italian",
    "southwestern",
    "spanish",
    "steakhouse",
    "street food",
    "sushi",
    "thai",
    "turkish",
    "vietnamese",
    "wine bar",
]

LOCATION_PATTERNS = [
    "gili air",
    "gili meno",
    "gili trawangan",
    "kuta",
    "lombok",
    "mataram",
    "pemenang",
    "senggigi",
]

MENU_PATTERNS = [
    "barbecue",
    "grill",
    "pizza",
    "seafood",
    "sushi",
]

MOOD_PATTERNS = [
    "a great place to spend",
    "a nice touch",
    "aglio olio pasta",
    "all you can eat",
    "amazing drinks",
    "amazing food",
    "amazing music",
    "amazing place",
    "amazing sunset",
    "amazing vegetarian food",
    "amazing views",
    "ambience",
    "an amazing dinner",
    "appetizers",
    "apple cider",
    "apple strudel",
    "arrabiata",
    "asia",
    "ate here",
    "atmosphere",
    "avocado",
    "awesome staff",
    "baguette",
    "bakery",
    "bali",
    "bali lombok",
    "bamboo",
    "band",
    "barracuda",
    "bases",
    "bbq",
    "bbq night",
    "beach",
    "beach front",
    "beachfront location",
    "bean bags",
    "beanbags",
    "beautiful beach",
    "beautiful place",
    "beautiful restaurant",
    "beautiful spot",
    "beautiful sunset",
    "beds",
    "beef",
    "beef rendang",
    "beef tartare",
    "beer",
    "beers",
    "best food on the island",
    "best pizza",
    "big prawns",
    "bintang",
    "birthday dinner",
    "bite",
    "boat",
    "bolognese",
    "boutique",
    "bowl",
    "bread",
    "breakfast or lunch",
    "brunch",
    "burger",
    "burrata",
    "burrito",
    "butter chicken",
    "butterfish",
    "cakes",
    "calamari",
    "carrot cake",
    "cat",
    "cheap eats",
    "cheese",
    "chef jiwa",
    "chicken",
    "chicken curry",
    "chicken katsu",
    "chicken kebab",
    "chill",
    "chilli",
    "chilli con carne",
    "chips",
    "cobb salad",
    "cocktails",
    "coconut",
    "coconut chicken",
    "cold beer",
    "colonial",
    "comfortable daybeds",
    "complimentary fresh fruit",
    "cooked beautifully",
    "cooked perfectly",
    "cooked simply",
    "cooking class",
    "cool interior",
    "cool vibe",
    "crispy",
    "croquetas",
    "croquettes",
    "crust",
    "culinary experience",
    "curries",
    "curry",
    "cute cafe",
    "day trip",
    "delicious food",
    "delicious seafood",
    "deserves a raise",
    "dessert",
    "diners",
    "dining experience",
    "dinner spot",
    "dips",
    "dirty burger",
    "discovery mall",
    "dish",
    "dishes",
    "don t miss",
    "dough",
    "driver",
    "duck",
    "during our stay",
    "edamame",
    "eggplant",
    "enjoyed happy hour",
    "enjoyed our stay",
    "every meal",
    "every morning",
    "every night",
    "executive chef",
    "extensive menu",
    "fabulous food",
    "fair trade",
    "fajitas",
    "falafel",
    "falafel wrap",
    "feta",
    "fine dining",
    "fire show",
    "fish",
    "focaccia",
    "food is excellent",
    "food was amazing",
    "food was great",
    "free soup",
    "french fries",
    "fresh fish",
    "fresh food",
    "fresh ingredients",
    "fresh juice",
    "fresh seafood",
    "friendly atmosphere",
    "friendly service",
    "fries",
    "frozen cocktails",
    "fruity",
    "gado gado",
    "garlic butter",
    "garlic naan",
    "gear",
    "gelato",
    "generator",
    "gets busy",
    "gili",
    "gili air",
    "gili islands",
    "gili t",
    "ginger",
    "golf cart",
    "good vibes",
    "granola bowl",
    "great atmosphere",
    "great band",
    "great cafe",
    "great cocktails",
    "great coffee",
    "great dinner",
    "great drinks",
    "great food",
    "great hotel",
    "great little restaurant",
    "great local food",
    "great lunch",
    "great meal",
    "great music",
    "great place to spend the day",
    "great seafood",
    "great sides",
    "great stay",
    "grilled to perfection",
    "grounds",
    "h2o",
    "hammocks",
    "happy hour",
    "happy hour on cocktails",
    "harbour",
    "hawaiian pizza",
    "hawkers",
    "hero",
    "homemade",
    "homemade chips",
    "hostel",
    "hot sauce",
    "hotel",
    "hotel restaurant",
    "ice cream",
    "iced latte",
    "indian food",
    "indonesia",
    "indonesian cuisine",
    "indonesian food",
    "indra",
    "ingredients",
    "irish bar",
    "island",
    "italian food",
    "italian owner",
    "jackfruit",
    "jalapeno poppers",
    "jamaican",
    "jamu",
    "juice",
    "katamaran",
    "kebab",
    "king prawns",
    "koi pond",
    "kuta beach",
    "large fish",
    "last night",
    "latte",
    "lemongrass",
    "limited menu",
    "limo",
    "limoncello",
    "live band",
    "live music",
    "live sports",
    "local dishes",
    "local experience",
    "local food",
    "local warung",
    "located right",
    "lombok",
    "lots of vegetarian options",
    "loungers",
    "love this place",
    "lovely evening",
    "lovely location",
    "lovely meal",
    "low season",
    "luca",
    "lunch",
    "lunch and dinner",
    "lunch or dinner",
    "mahi mahi",
    "mai tai",
    "mains",
    "mango",
    "mango juice",
    "mangsit beach",
    "margarita",
    "margaritas",
    "meats",
    "mexican food",
    "meyer",
    "mie goreng",
    "milkshakes",
    "mocktails",
    "mollys",
    "moyo",
    "mozzarella",
    "my boyfriend",
    "nachos",
    "nasi goreng",
    "nice atmosphere",
    "nice cocktails",
    "nice dinner",
    "nice food",
    "nice food and drinks",
    "nice meal",
    "nice place",
    "nice place and good food",
    "nice restaurant",
    "nice service",
    "nice setting",
    "nice venue",
    "nice view",
    "night market",
    "noodles",
    "ocean",
    "oil",
    "olah olah",
    "oreo cheesecake",
    "other places",
    "our honeymoon",
    "our night stay",
    "our short stay",
    "our waiter",
    "pad thai",
    "paella",
    "pancakes",
    "paradise",
    "parmesan fries",
    "parmigiana",
    "pasta",
    "pastry",
    "patatas bravas",
    "pepes",
    "perfect spot",
    "perfect sunset",
    "pita",
    "pizza",
    "place to stay",
    "platter",
    "pool",
    "pool bar",
    "pork sandwich",
    "portions",
    "potatoes",
    "power",
    "prawns",
    "presentation",
    "private dinner",
    "putra",
    "quality of food",
    "quick service",
    "qunci villas",
    "ramadan",
    "recommend this restaurant",
    "red curry",
    "red snapper",
    "rendang",
    "resort",
    "resto",
    "ribs",
    "rice",
    "rijsttafel",
    "risotto",
    "roast chicken",
    "romantic dinner",
    "room service",
    "rosemary chips",
    "roy",
    "sabor",
    "salad",
    "salad bar",
    "salmon",
    "sand",
    "sandwich",
    "sandwiches",
    "sangria",
    "sat upstairs",
    "satay",
    "sate",
    "sauce",
    "scooter",
    "sea",
    "sea view",
    "seafood",
    "seafood platter",
    "senggigi",
    "senggigi beach",
    "service was excellent",
    "service was great",
    "service was impeccable",
    "sesame",
    "set",
    "shark bites",
    "shisha",
    "shore",
    "shower",
    "shrimp",
    "siciliana",
    "side dishes",
    "signature cocktails",
    "skewers",
    "small island",
    "small restaurant",
    "smoothies",
    "sotong",
    "soup",
    "spicy",
    "spicy beef",
    "spring rolls",
    "square",
    "stalls",
    "star service",
    "starters",
    "stay",
    "stayed here for nights",
    "steak",
    "sticks",
    "stir fry",
    "stopped for lunch",
    "sudamala",
    "sunbeds",
    "sunset",
    "sunset view",
    "super friendly staff",
    "super fun",
    "super tasty",
    "surfing",
    "sushi",
    "sweetest",
    "swim",
    "swim up bar",
    "swimming pool",
    "taco",
    "tacos",
    "tagliatelle",
    "take away",
    "taman",
    "tapas",
    "taste",
    "tasty food",
    "tempe",
    "tempura",
    "tequila sunrise",
    "terima kasih",
    "teriyaki",
    "thai",
    "the main road",
    "the main strip",
    "the owner",
    "the pearl",
    "the perfect spot",
    "thin crust",
    "tiramisu",
    "tissa",
    "toppings",
    "tortillas",
    "trawangan",
    "trees",
    "trench town",
    "tuna",
    "tuna burger",
    "tuna tostada",
    "turtles",
    "uncle",
    "urap urap",
    "varied menu",
    "vegan",
    "vegan ice cream",
    "vegetables",
    "vegetarian",
    "vegetarian food",
    "vegetarian options",
    "vibe",
    "vibes",
    "views",
    "villa",
    "visit lombok",
    "visited times",
    "waiter",
    "waiters",
    "warung",
    "watch the sunset",
    "watching the sunset",
    "watermelon salad",
    "waves",
    "wedges",
    "white chocolate",
    "white sand beach",
    "wilsons",
    "wine list",
    "wrap",
    "wraps",
    "yakiniku",
    "yellow curry",
    "yellow fin",
    "yoga",
    "yum",
    "yummy",
]

FEATURES_PATTERNS = [
    "accepts credit cards",
    "american express",
    "beach",
    "buffet",
    "byob",
    "cash only",
    "delivery",
    "digital payments",
    "dog friendly",
    "drive thru",
    "family style",
    "free off-street parking",
    "free wifi",
    "full bar",
    "gift cards available",
    "highchairs available",
    "jazz bar",
    "live music",
    "mastercard",
    "non-smoking restaurants",
    "outdoor seating",
    "parking available",
    "playgrounds",
    "private dining",
    "reservations",
    "seating",
    "serves alcohol",
    "sports bars",
    "street parking",
    "table service",
    "takeout",
    "television",
    "valet parking",
    "validated parking",
    "visa",
    "waterfront",
    "wheelchair accessible",
    "wine and beer",
]
